/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAskRouteImport } from './routes/_authenticated/ask'
import { Route as AuthenticatedBackupsRouteImport } from './routes/_authenticated/backups'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedEmailsRouteImport } from './routes/_authenticated/emails'
import { Route as AuthenticatedFffRouteImport } from './routes/_authenticated/fff'
import { Route as AuthenticatedQueuesRouteImport } from './routes/_authenticated/queues'
import { Route as AuthenticatedQuotationsRouteImport } from './routes/_authenticated/quotations'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedTimelineRouteImport } from './routes/_authenticated/timeline'
import { Route as ApiSendSampleEmailRouteImport } from './routes/api/send-sample-email'
import { Route as DTokenRouteImport } from './routes/d.$token'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedContainersIndexRouteImport } from './routes/_authenticated/containers/index'
import { Route as AuthenticatedContainersBoxIdRouteImport } from './routes/_authenticated/containers/$boxId'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as AuthenticatedKeywordsIndexRouteImport } from './routes/_authenticated/keywords/index'
import { Route as AuthenticatedKeywordsKeywordIdRouteImport } from './routes/_authenticated/keywords/$keywordId'
import { Route as AuthenticatedLettersIndexRouteImport } from './routes/_authenticated/letters/index'
import { Route as AuthenticatedLettersArchiveIdRouteImport } from './routes/_authenticated/letters/$archiveId'
import { Route as AuthenticatedOrganizationsIndexRouteImport } from './routes/_authenticated/organizations/index'
import { Route as AuthenticatedPeopleIndexRouteImport } from './routes/_authenticated/people/index'
import { Route as AuthenticatedPeoplePersonIdRouteImport } from './routes/_authenticated/people/$personId'
import { Route as AuthenticatedPlacesIndexRouteImport } from './routes/_authenticated/places/index'
import { Route as AuthenticatedPlacesPlaceIdRouteImport } from './routes/_authenticated/places/$placeId'
import { Route as AuthenticatedRecapsIndexRouteImport } from './routes/_authenticated/recaps/index'
import { Route as AuthenticatedSourcesIndexRouteImport } from './routes/_authenticated/sources/index'
import { Route as AuthenticatedSourcesDsIdRouteImport } from './routes/_authenticated/sources/$dsId'
import { Route as AuthenticatedSourcesNewRouteImport } from './routes/_authenticated/sources/new'
import { Route as ApiPublicArchivistDigestRouteImport } from './routes/api/public/archivist-digest'
import { Route as ApiPublicBackupRouteImport } from './routes/api/public/backup'
import { Route as ApiPublicResearchSnapshotRouteImport } from './routes/api/public/research-snapshot'
import { Route as ApiPublicWeeklyRecapRouteImport } from './routes/api/public/weekly-recap'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAskRoute = AuthenticatedAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackupsRoute = AuthenticatedBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailsRoute = AuthenticatedEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFffRoute = AuthenticatedFffRouteImport.update({
  id: '/fff',
  path: '/fff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueuesRoute = AuthenticatedQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsRoute = AuthenticatedQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimelineRoute = AuthenticatedTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiSendSampleEmailRoute = ApiSendSampleEmailRouteImport.update({
  id: '/api/send-sample-email',
  path: '/api/send-sample-email',
  getParentRoute: () => rootRouteImport,
} as any)
const DTokenRoute = DTokenRouteImport.update({
  id: '/d/$token',
  path: '/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContainersIndexRoute =
  AuthenticatedContainersIndexRouteImport.update({
    id: '/containers/',
    path: '/containers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContainersBoxIdRoute =
  AuthenticatedContainersBoxIdRouteImport.update({
    id: '/containers/$boxId',
    path: '/containers/$boxId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKeywordsIndexRoute =
  AuthenticatedKeywordsIndexRouteImport.update({
    id: '/keywords/',
    path: '/keywords/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKeywordsKeywordIdRoute =
  AuthenticatedKeywordsKeywordIdRouteImport.update({
    id: '/keywords/$keywordId',
    path: '/keywords/$keywordId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLettersIndexRoute =
  AuthenticatedLettersIndexRouteImport.update({
    id: '/letters/',
    path: '/letters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLettersArchiveIdRoute =
  AuthenticatedLettersArchiveIdRouteImport.update({
    id: '/letters/$archiveId',
    path: '/letters/$archiveId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationsIndexRoute =
  AuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleIndexRoute =
  AuthenticatedPeopleIndexRouteImport.update({
    id: '/people/',
    path: '/people/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeoplePersonIdRoute =
  AuthenticatedPeoplePersonIdRouteImport.update({
    id: '/people/$personId',
    path: '/people/$personId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlacesIndexRoute =
  AuthenticatedPlacesIndexRouteImport.update({
    id: '/places/',
    path: '/places/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlacesPlaceIdRoute =
  AuthenticatedPlacesPlaceIdRouteImport.update({
    id: '/places/$placeId',
    path: '/places/$placeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecapsIndexRoute =
  AuthenticatedRecapsIndexRouteImport.update({
    id: '/recaps/',
    path: '/recaps/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSourcesIndexRoute =
  AuthenticatedSourcesIndexRouteImport.update({
    id: '/sources/',
    path: '/sources/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSourcesDsIdRoute =
  AuthenticatedSourcesDsIdRouteImport.update({
    id: '/sources/$dsId',
    path: '/sources/$dsId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSourcesNewRoute = AuthenticatedSourcesNewRouteImport.update({
  id: '/sources/new',
  path: '/sources/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicArchivistDigestRoute =
  ApiPublicArchivistDigestRouteImport.update({
    id: '/api/public/archivist-digest',
    path: '/api/public/archivist-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBackupRoute = ApiPublicBackupRouteImport.update({
  id: '/api/public/backup',
  path: '/api/public/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResearchSnapshotRoute =
  ApiPublicResearchSnapshotRouteImport.update({
    id: '/api/public/research-snapshot',
    path: '/api/public/research-snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWeeklyRecapRoute = ApiPublicWeeklyRecapRouteImport.update({
  id: '/api/public/weekly-recap',
  path: '/api/public/weekly-recap',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ask': typeof AuthenticatedAskRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/fff': typeof AuthenticatedFffRoute
  '/queues': typeof AuthenticatedQueuesRoute
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/api/send-sample-email': typeof ApiSendSampleEmailRoute
  '/d/$token': typeof DTokenRoute
  '/s/$token': typeof STokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/containers/$boxId': typeof AuthenticatedContainersBoxIdRoute
  '/keywords/$keywordId': typeof AuthenticatedKeywordsKeywordIdRoute
  '/letters/$archiveId': typeof AuthenticatedLettersArchiveIdRoute
  '/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/places/$placeId': typeof AuthenticatedPlacesPlaceIdRoute
  '/sources/$dsId': typeof AuthenticatedSourcesDsIdRoute
  '/sources/new': typeof AuthenticatedSourcesNewRoute
  '/api/public/archivist-digest': typeof ApiPublicArchivistDigestRoute
  '/api/public/backup': typeof ApiPublicBackupRoute
  '/api/public/research-snapshot': typeof ApiPublicResearchSnapshotRoute
  '/api/public/weekly-recap': typeof ApiPublicWeeklyRecapRoute
  '/containers/': typeof AuthenticatedContainersIndexRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/keywords/': typeof AuthenticatedKeywordsIndexRoute
  '/letters/': typeof AuthenticatedLettersIndexRoute
  '/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/people/': typeof AuthenticatedPeopleIndexRoute
  '/places/': typeof AuthenticatedPlacesIndexRoute
  '/recaps/': typeof AuthenticatedRecapsIndexRoute
  '/sources/': typeof AuthenticatedSourcesIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ask': typeof AuthenticatedAskRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/fff': typeof AuthenticatedFffRoute
  '/queues': typeof AuthenticatedQueuesRoute
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/api/send-sample-email': typeof ApiSendSampleEmailRoute
  '/d/$token': typeof DTokenRoute
  '/s/$token': typeof STokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/containers/$boxId': typeof AuthenticatedContainersBoxIdRoute
  '/keywords/$keywordId': typeof AuthenticatedKeywordsKeywordIdRoute
  '/letters/$archiveId': typeof AuthenticatedLettersArchiveIdRoute
  '/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/places/$placeId': typeof AuthenticatedPlacesPlaceIdRoute
  '/sources/$dsId': typeof AuthenticatedSourcesDsIdRoute
  '/sources/new': typeof AuthenticatedSourcesNewRoute
  '/api/public/archivist-digest': typeof ApiPublicArchivistDigestRoute
  '/api/public/backup': typeof ApiPublicBackupRoute
  '/api/public/research-snapshot': typeof ApiPublicResearchSnapshotRoute
  '/api/public/weekly-recap': typeof ApiPublicWeeklyRecapRoute
  '/containers': typeof AuthenticatedContainersIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/keywords': typeof AuthenticatedKeywordsIndexRoute
  '/letters': typeof AuthenticatedLettersIndexRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/people': typeof AuthenticatedPeopleIndexRoute
  '/places': typeof AuthenticatedPlacesIndexRoute
  '/recaps': typeof AuthenticatedRecapsIndexRoute
  '/sources': typeof AuthenticatedSourcesIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/ask': typeof AuthenticatedAskRoute
  '/_authenticated/backups': typeof AuthenticatedBackupsRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/emails': typeof AuthenticatedEmailsRoute
  '/_authenticated/fff': typeof AuthenticatedFffRoute
  '/_authenticated/queues': typeof AuthenticatedQueuesRoute
  '/_authenticated/quotations': typeof AuthenticatedQuotationsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/timeline': typeof AuthenticatedTimelineRoute
  '/api/send-sample-email': typeof ApiSendSampleEmailRoute
  '/d/$token': typeof DTokenRoute
  '/s/$token': typeof STokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/containers/$boxId': typeof AuthenticatedContainersBoxIdRoute
  '/_authenticated/keywords/$keywordId': typeof AuthenticatedKeywordsKeywordIdRoute
  '/_authenticated/letters/$archiveId': typeof AuthenticatedLettersArchiveIdRoute
  '/_authenticated/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/_authenticated/places/$placeId': typeof AuthenticatedPlacesPlaceIdRoute
  '/_authenticated/sources/$dsId': typeof AuthenticatedSourcesDsIdRoute
  '/_authenticated/sources/new': typeof AuthenticatedSourcesNewRoute
  '/api/public/archivist-digest': typeof ApiPublicArchivistDigestRoute
  '/api/public/backup': typeof ApiPublicBackupRoute
  '/api/public/research-snapshot': typeof ApiPublicResearchSnapshotRoute
  '/api/public/weekly-recap': typeof ApiPublicWeeklyRecapRoute
  '/_authenticated/containers/': typeof AuthenticatedContainersIndexRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/keywords/': typeof AuthenticatedKeywordsIndexRoute
  '/_authenticated/letters/': typeof AuthenticatedLettersIndexRoute
  '/_authenticated/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/_authenticated/people/': typeof AuthenticatedPeopleIndexRoute
  '/_authenticated/places/': typeof AuthenticatedPlacesIndexRoute
  '/_authenticated/recaps/': typeof AuthenticatedRecapsIndexRoute
  '/_authenticated/sources/': typeof AuthenticatedSourcesIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ask'
    | '/backups'
    | '/catalog'
    | '/categories'
    | '/emails'
    | '/fff'
    | '/queues'
    | '/quotations'
    | '/search'
    | '/timeline'
    | '/api/send-sample-email'
    | '/d/$token'
    | '/s/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/users'
    | '/containers/$boxId'
    | '/keywords/$keywordId'
    | '/letters/$archiveId'
    | '/people/$personId'
    | '/places/$placeId'
    | '/sources/$dsId'
    | '/sources/new'
    | '/api/public/archivist-digest'
    | '/api/public/backup'
    | '/api/public/research-snapshot'
    | '/api/public/weekly-recap'
    | '/containers/'
    | '/events/'
    | '/keywords/'
    | '/letters/'
    | '/organizations/'
    | '/people/'
    | '/places/'
    | '/recaps/'
    | '/sources/'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/forgot-password'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ask'
    | '/backups'
    | '/catalog'
    | '/categories'
    | '/emails'
    | '/fff'
    | '/queues'
    | '/quotations'
    | '/search'
    | '/timeline'
    | '/api/send-sample-email'
    | '/d/$token'
    | '/s/$token'
    | '/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/users'
    | '/containers/$boxId'
    | '/keywords/$keywordId'
    | '/letters/$archiveId'
    | '/people/$personId'
    | '/places/$placeId'
    | '/sources/$dsId'
    | '/sources/new'
    | '/api/public/archivist-digest'
    | '/api/public/backup'
    | '/api/public/research-snapshot'
    | '/api/public/weekly-recap'
    | '/containers'
    | '/events'
    | '/keywords'
    | '/letters'
    | '/organizations'
    | '/people'
    | '/places'
    | '/recaps'
    | '/sources'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/ask'
    | '/_authenticated/backups'
    | '/_authenticated/catalog'
    | '/_authenticated/categories'
    | '/_authenticated/emails'
    | '/_authenticated/fff'
    | '/_authenticated/queues'
    | '/_authenticated/quotations'
    | '/_authenticated/search'
    | '/_authenticated/timeline'
    | '/api/send-sample-email'
    | '/d/$token'
    | '/s/$token'
    | '/_authenticated/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/users'
    | '/_authenticated/containers/$boxId'
    | '/_authenticated/keywords/$keywordId'
    | '/_authenticated/letters/$archiveId'
    | '/_authenticated/people/$personId'
    | '/_authenticated/places/$placeId'
    | '/_authenticated/sources/$dsId'
    | '/_authenticated/sources/new'
    | '/api/public/archivist-digest'
    | '/api/public/backup'
    | '/api/public/research-snapshot'
    | '/api/public/weekly-recap'
    | '/_authenticated/containers/'
    | '/_authenticated/events/'
    | '/_authenticated/keywords/'
    | '/_authenticated/letters/'
    | '/_authenticated/organizations/'
    | '/_authenticated/people/'
    | '/_authenticated/places/'
    | '/_authenticated/recaps/'
    | '/_authenticated/sources/'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiSendSampleEmailRoute: typeof ApiSendSampleEmailRoute
  DTokenRoute: typeof DTokenRoute
  STokenRoute: typeof STokenRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicArchivistDigestRoute: typeof ApiPublicArchivistDigestRoute
  ApiPublicBackupRoute: typeof ApiPublicBackupRoute
  ApiPublicResearchSnapshotRoute: typeof ApiPublicResearchSnapshotRoute
  ApiPublicWeeklyRecapRoute: typeof ApiPublicWeeklyRecapRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ask': {
      id: '/_authenticated/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backups': {
      id: '/_authenticated/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthenticatedBackupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emails': {
      id: '/_authenticated/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof AuthenticatedEmailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fff': {
      id: '/_authenticated/fff'
      path: '/fff'
      fullPath: '/fff'
      preLoaderRoute: typeof AuthenticatedFffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queues': {
      id: '/_authenticated/queues'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof AuthenticatedQueuesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations': {
      id: '/_authenticated/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AuthenticatedQuotationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timeline': {
      id: '/_authenticated/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthenticatedTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/send-sample-email': {
      id: '/api/send-sample-email'
      path: '/api/send-sample-email'
      fullPath: '/api/send-sample-email'
      preLoaderRoute: typeof ApiSendSampleEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$token': {
      id: '/d/$token'
      path: '/d/$token'
      fullPath: '/d/$token'
      preLoaderRoute: typeof DTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/containers/': {
      id: '/_authenticated/containers/'
      path: '/containers'
      fullPath: '/containers/'
      preLoaderRoute: typeof AuthenticatedContainersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/containers/$boxId': {
      id: '/_authenticated/containers/$boxId'
      path: '/containers/$boxId'
      fullPath: '/containers/$boxId'
      preLoaderRoute: typeof AuthenticatedContainersBoxIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keywords/': {
      id: '/_authenticated/keywords/'
      path: '/keywords'
      fullPath: '/keywords/'
      preLoaderRoute: typeof AuthenticatedKeywordsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keywords/$keywordId': {
      id: '/_authenticated/keywords/$keywordId'
      path: '/keywords/$keywordId'
      fullPath: '/keywords/$keywordId'
      preLoaderRoute: typeof AuthenticatedKeywordsKeywordIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/letters/': {
      id: '/_authenticated/letters/'
      path: '/letters'
      fullPath: '/letters/'
      preLoaderRoute: typeof AuthenticatedLettersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/letters/$archiveId': {
      id: '/_authenticated/letters/$archiveId'
      path: '/letters/$archiveId'
      fullPath: '/letters/$archiveId'
      preLoaderRoute: typeof AuthenticatedLettersArchiveIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations/': {
      id: '/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/': {
      id: '/_authenticated/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthenticatedPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/$personId': {
      id: '/_authenticated/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AuthenticatedPeoplePersonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/places/': {
      id: '/_authenticated/places/'
      path: '/places'
      fullPath: '/places/'
      preLoaderRoute: typeof AuthenticatedPlacesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/places/$placeId': {
      id: '/_authenticated/places/$placeId'
      path: '/places/$placeId'
      fullPath: '/places/$placeId'
      preLoaderRoute: typeof AuthenticatedPlacesPlaceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recaps/': {
      id: '/_authenticated/recaps/'
      path: '/recaps'
      fullPath: '/recaps/'
      preLoaderRoute: typeof AuthenticatedRecapsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sources/': {
      id: '/_authenticated/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof AuthenticatedSourcesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sources/$dsId': {
      id: '/_authenticated/sources/$dsId'
      path: '/sources/$dsId'
      fullPath: '/sources/$dsId'
      preLoaderRoute: typeof AuthenticatedSourcesDsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sources/new': {
      id: '/_authenticated/sources/new'
      path: '/sources/new'
      fullPath: '/sources/new'
      preLoaderRoute: typeof AuthenticatedSourcesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/archivist-digest': {
      id: '/api/public/archivist-digest'
      path: '/api/public/archivist-digest'
      fullPath: '/api/public/archivist-digest'
      preLoaderRoute: typeof ApiPublicArchivistDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backup': {
      id: '/api/public/backup'
      path: '/api/public/backup'
      fullPath: '/api/public/backup'
      preLoaderRoute: typeof ApiPublicBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/research-snapshot': {
      id: '/api/public/research-snapshot'
      path: '/api/public/research-snapshot'
      fullPath: '/api/public/research-snapshot'
      preLoaderRoute: typeof ApiPublicResearchSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/weekly-recap': {
      id: '/api/public/weekly-recap'
      path: '/api/public/weekly-recap'
      fullPath: '/api/public/weekly-recap'
      preLoaderRoute: typeof ApiPublicWeeklyRecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAskRoute: typeof AuthenticatedAskRoute
  AuthenticatedBackupsRoute: typeof AuthenticatedBackupsRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedEmailsRoute: typeof AuthenticatedEmailsRoute
  AuthenticatedFffRoute: typeof AuthenticatedFffRoute
  AuthenticatedQueuesRoute: typeof AuthenticatedQueuesRoute
  AuthenticatedQuotationsRoute: typeof AuthenticatedQuotationsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedTimelineRoute: typeof AuthenticatedTimelineRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedContainersBoxIdRoute: typeof AuthenticatedContainersBoxIdRoute
  AuthenticatedKeywordsKeywordIdRoute: typeof AuthenticatedKeywordsKeywordIdRoute
  AuthenticatedLettersArchiveIdRoute: typeof AuthenticatedLettersArchiveIdRoute
  AuthenticatedPeoplePersonIdRoute: typeof AuthenticatedPeoplePersonIdRoute
  AuthenticatedPlacesPlaceIdRoute: typeof AuthenticatedPlacesPlaceIdRoute
  AuthenticatedSourcesDsIdRoute: typeof AuthenticatedSourcesDsIdRoute
  AuthenticatedSourcesNewRoute: typeof AuthenticatedSourcesNewRoute
  AuthenticatedContainersIndexRoute: typeof AuthenticatedContainersIndexRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedKeywordsIndexRoute: typeof AuthenticatedKeywordsIndexRoute
  AuthenticatedLettersIndexRoute: typeof AuthenticatedLettersIndexRoute
  AuthenticatedOrganizationsIndexRoute: typeof AuthenticatedOrganizationsIndexRoute
  AuthenticatedPeopleIndexRoute: typeof AuthenticatedPeopleIndexRoute
  AuthenticatedPlacesIndexRoute: typeof AuthenticatedPlacesIndexRoute
  AuthenticatedRecapsIndexRoute: typeof AuthenticatedRecapsIndexRoute
  AuthenticatedSourcesIndexRoute: typeof AuthenticatedSourcesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAskRoute: AuthenticatedAskRoute,
  AuthenticatedBackupsRoute: AuthenticatedBackupsRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedEmailsRoute: AuthenticatedEmailsRoute,
  AuthenticatedFffRoute: AuthenticatedFffRoute,
  AuthenticatedQueuesRoute: AuthenticatedQueuesRoute,
  AuthenticatedQuotationsRoute: AuthenticatedQuotationsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedTimelineRoute: AuthenticatedTimelineRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedContainersBoxIdRoute: AuthenticatedContainersBoxIdRoute,
  AuthenticatedKeywordsKeywordIdRoute: AuthenticatedKeywordsKeywordIdRoute,
  AuthenticatedLettersArchiveIdRoute: AuthenticatedLettersArchiveIdRoute,
  AuthenticatedPeoplePersonIdRoute: AuthenticatedPeoplePersonIdRoute,
  AuthenticatedPlacesPlaceIdRoute: AuthenticatedPlacesPlaceIdRoute,
  AuthenticatedSourcesDsIdRoute: AuthenticatedSourcesDsIdRoute,
  AuthenticatedSourcesNewRoute: AuthenticatedSourcesNewRoute,
  AuthenticatedContainersIndexRoute: AuthenticatedContainersIndexRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedKeywordsIndexRoute: AuthenticatedKeywordsIndexRoute,
  AuthenticatedLettersIndexRoute: AuthenticatedLettersIndexRoute,
  AuthenticatedOrganizationsIndexRoute: AuthenticatedOrganizationsIndexRoute,
  AuthenticatedPeopleIndexRoute: AuthenticatedPeopleIndexRoute,
  AuthenticatedPlacesIndexRoute: AuthenticatedPlacesIndexRoute,
  AuthenticatedRecapsIndexRoute: AuthenticatedRecapsIndexRoute,
  AuthenticatedSourcesIndexRoute: AuthenticatedSourcesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiSendSampleEmailRoute: ApiSendSampleEmailRoute,
  DTokenRoute: DTokenRoute,
  STokenRoute: STokenRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicArchivistDigestRoute: ApiPublicArchivistDigestRoute,
  ApiPublicBackupRoute: ApiPublicBackupRoute,
  ApiPublicResearchSnapshotRoute: ApiPublicResearchSnapshotRoute,
  ApiPublicWeeklyRecapRoute: ApiPublicWeeklyRecapRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
