/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBackupsRouteImport } from './routes/_authenticated/backups'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedEmailsRouteImport } from './routes/_authenticated/emails'
import { Route as AuthenticatedQueuesRouteImport } from './routes/_authenticated/queues'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedTimelineRouteImport } from './routes/_authenticated/timeline'
import { Route as DTokenRouteImport } from './routes/d.$token'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as AuthenticatedContainersIndexRouteImport } from './routes/_authenticated/containers/index'
import { Route as AuthenticatedContainersBoxIdRouteImport } from './routes/_authenticated/containers/$boxId'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as AuthenticatedKeywordsIndexRouteImport } from './routes/_authenticated/keywords/index'
import { Route as AuthenticatedKeywordsKeywordIdRouteImport } from './routes/_authenticated/keywords/$keywordId'
import { Route as AuthenticatedLettersIndexRouteImport } from './routes/_authenticated/letters/index'
import { Route as AuthenticatedLettersArchiveIdRouteImport } from './routes/_authenticated/letters/$archiveId'
import { Route as AuthenticatedOrganizationsIndexRouteImport } from './routes/_authenticated/organizations/index'
import { Route as AuthenticatedPeopleIndexRouteImport } from './routes/_authenticated/people/index'
import { Route as AuthenticatedPeoplePersonIdRouteImport } from './routes/_authenticated/people/$personId'
import { Route as AuthenticatedPlacesIndexRouteImport } from './routes/_authenticated/places/index'
import { Route as AuthenticatedPlacesPlaceIdRouteImport } from './routes/_authenticated/places/$placeId'
import { Route as AuthenticatedSourcesIndexRouteImport } from './routes/_authenticated/sources/index'
import { Route as AuthenticatedSourcesDsIdRouteImport } from './routes/_authenticated/sources/$dsId'
import { Route as AuthenticatedSourcesNewRouteImport } from './routes/_authenticated/sources/new'
import { Route as ApiPublicBackupRouteImport } from './routes/api/public/backup'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBackupsRoute = AuthenticatedBackupsRouteImport.update({
  id: '/_authenticated/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/_authenticated/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/_authenticated/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEmailsRoute = AuthenticatedEmailsRouteImport.update({
  id: '/_authenticated/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQueuesRoute = AuthenticatedQueuesRouteImport.update({
  id: '/_authenticated/queues',
  path: '/queues',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/_authenticated/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimelineRoute = AuthenticatedTimelineRouteImport.update({
  id: '/_authenticated/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const DTokenRoute = DTokenRouteImport.update({
  id: '/d/$token',
  path: '/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContainersIndexRoute =
  AuthenticatedContainersIndexRouteImport.update({
    id: '/_authenticated/containers/',
    path: '/containers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedContainersBoxIdRoute =
  AuthenticatedContainersBoxIdRouteImport.update({
    id: '/_authenticated/containers/$boxId',
    path: '/containers/$boxId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/_authenticated/events/',
    path: '/events/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedKeywordsIndexRoute =
  AuthenticatedKeywordsIndexRouteImport.update({
    id: '/_authenticated/keywords/',
    path: '/keywords/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedKeywordsKeywordIdRoute =
  AuthenticatedKeywordsKeywordIdRouteImport.update({
    id: '/_authenticated/keywords/$keywordId',
    path: '/keywords/$keywordId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLettersIndexRoute =
  AuthenticatedLettersIndexRouteImport.update({
    id: '/_authenticated/letters/',
    path: '/letters/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLettersArchiveIdRoute =
  AuthenticatedLettersArchiveIdRouteImport.update({
    id: '/_authenticated/letters/$archiveId',
    path: '/letters/$archiveId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOrganizationsIndexRoute =
  AuthenticatedOrganizationsIndexRouteImport.update({
    id: '/_authenticated/organizations/',
    path: '/organizations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPeopleIndexRoute =
  AuthenticatedPeopleIndexRouteImport.update({
    id: '/_authenticated/people/',
    path: '/people/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPeoplePersonIdRoute =
  AuthenticatedPeoplePersonIdRouteImport.update({
    id: '/_authenticated/people/$personId',
    path: '/people/$personId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPlacesIndexRoute =
  AuthenticatedPlacesIndexRouteImport.update({
    id: '/_authenticated/places/',
    path: '/places/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPlacesPlaceIdRoute =
  AuthenticatedPlacesPlaceIdRouteImport.update({
    id: '/_authenticated/places/$placeId',
    path: '/places/$placeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSourcesIndexRoute =
  AuthenticatedSourcesIndexRouteImport.update({
    id: '/_authenticated/sources/',
    path: '/sources/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSourcesDsIdRoute =
  AuthenticatedSourcesDsIdRouteImport.update({
    id: '/_authenticated/sources/$dsId',
    path: '/sources/$dsId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSourcesNewRoute = AuthenticatedSourcesNewRouteImport.update({
  id: '/_authenticated/sources/new',
  path: '/sources/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackupRoute = ApiPublicBackupRouteImport.update({
  id: '/api/public/backup',
  path: '/api/public/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/queues': typeof AuthenticatedQueuesRoute
  '/search': typeof AuthenticatedSearchRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/d/$token': typeof DTokenRoute
  '/s/$token': typeof STokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/containers/$boxId': typeof AuthenticatedContainersBoxIdRoute
  '/keywords/$keywordId': typeof AuthenticatedKeywordsKeywordIdRoute
  '/letters/$archiveId': typeof AuthenticatedLettersArchiveIdRoute
  '/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/places/$placeId': typeof AuthenticatedPlacesPlaceIdRoute
  '/sources/$dsId': typeof AuthenticatedSourcesDsIdRoute
  '/sources/new': typeof AuthenticatedSourcesNewRoute
  '/api/public/backup': typeof ApiPublicBackupRoute
  '/containers/': typeof AuthenticatedContainersIndexRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/keywords/': typeof AuthenticatedKeywordsIndexRoute
  '/letters/': typeof AuthenticatedLettersIndexRoute
  '/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/people/': typeof AuthenticatedPeopleIndexRoute
  '/places/': typeof AuthenticatedPlacesIndexRoute
  '/sources/': typeof AuthenticatedSourcesIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/queues': typeof AuthenticatedQueuesRoute
  '/search': typeof AuthenticatedSearchRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/d/$token': typeof DTokenRoute
  '/s/$token': typeof STokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/containers/$boxId': typeof AuthenticatedContainersBoxIdRoute
  '/keywords/$keywordId': typeof AuthenticatedKeywordsKeywordIdRoute
  '/letters/$archiveId': typeof AuthenticatedLettersArchiveIdRoute
  '/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/places/$placeId': typeof AuthenticatedPlacesPlaceIdRoute
  '/sources/$dsId': typeof AuthenticatedSourcesDsIdRoute
  '/sources/new': typeof AuthenticatedSourcesNewRoute
  '/api/public/backup': typeof ApiPublicBackupRoute
  '/containers': typeof AuthenticatedContainersIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/keywords': typeof AuthenticatedKeywordsIndexRoute
  '/letters': typeof AuthenticatedLettersIndexRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/people': typeof AuthenticatedPeopleIndexRoute
  '/places': typeof AuthenticatedPlacesIndexRoute
  '/sources': typeof AuthenticatedSourcesIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/backups': typeof AuthenticatedBackupsRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/emails': typeof AuthenticatedEmailsRoute
  '/_authenticated/queues': typeof AuthenticatedQueuesRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/timeline': typeof AuthenticatedTimelineRoute
  '/d/$token': typeof DTokenRoute
  '/s/$token': typeof STokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/containers/$boxId': typeof AuthenticatedContainersBoxIdRoute
  '/_authenticated/keywords/$keywordId': typeof AuthenticatedKeywordsKeywordIdRoute
  '/_authenticated/letters/$archiveId': typeof AuthenticatedLettersArchiveIdRoute
  '/_authenticated/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/_authenticated/places/$placeId': typeof AuthenticatedPlacesPlaceIdRoute
  '/_authenticated/sources/$dsId': typeof AuthenticatedSourcesDsIdRoute
  '/_authenticated/sources/new': typeof AuthenticatedSourcesNewRoute
  '/api/public/backup': typeof ApiPublicBackupRoute
  '/_authenticated/containers/': typeof AuthenticatedContainersIndexRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/keywords/': typeof AuthenticatedKeywordsIndexRoute
  '/_authenticated/letters/': typeof AuthenticatedLettersIndexRoute
  '/_authenticated/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/_authenticated/people/': typeof AuthenticatedPeopleIndexRoute
  '/_authenticated/places/': typeof AuthenticatedPlacesIndexRoute
  '/_authenticated/sources/': typeof AuthenticatedSourcesIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/backups'
    | '/catalog'
    | '/categories'
    | '/emails'
    | '/queues'
    | '/search'
    | '/timeline'
    | '/d/$token'
    | '/s/$token'
    | '/'
    | '/containers/$boxId'
    | '/keywords/$keywordId'
    | '/letters/$archiveId'
    | '/people/$personId'
    | '/places/$placeId'
    | '/sources/$dsId'
    | '/sources/new'
    | '/api/public/backup'
    | '/containers/'
    | '/events/'
    | '/keywords/'
    | '/letters/'
    | '/organizations/'
    | '/people/'
    | '/places/'
    | '/sources/'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/backups'
    | '/catalog'
    | '/categories'
    | '/emails'
    | '/queues'
    | '/search'
    | '/timeline'
    | '/d/$token'
    | '/s/$token'
    | '/'
    | '/containers/$boxId'
    | '/keywords/$keywordId'
    | '/letters/$archiveId'
    | '/people/$personId'
    | '/places/$placeId'
    | '/sources/$dsId'
    | '/sources/new'
    | '/api/public/backup'
    | '/containers'
    | '/events'
    | '/keywords'
    | '/letters'
    | '/organizations'
    | '/people'
    | '/places'
    | '/sources'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/backups'
    | '/_authenticated/catalog'
    | '/_authenticated/categories'
    | '/_authenticated/emails'
    | '/_authenticated/queues'
    | '/_authenticated/search'
    | '/_authenticated/timeline'
    | '/d/$token'
    | '/s/$token'
    | '/_authenticated/'
    | '/_authenticated/containers/$boxId'
    | '/_authenticated/keywords/$keywordId'
    | '/_authenticated/letters/$archiveId'
    | '/_authenticated/people/$personId'
    | '/_authenticated/places/$placeId'
    | '/_authenticated/sources/$dsId'
    | '/_authenticated/sources/new'
    | '/api/public/backup'
    | '/_authenticated/containers/'
    | '/_authenticated/events/'
    | '/_authenticated/keywords/'
    | '/_authenticated/letters/'
    | '/_authenticated/organizations/'
    | '/_authenticated/people/'
    | '/_authenticated/places/'
    | '/_authenticated/sources/'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthenticatedBackupsRoute: typeof AuthenticatedBackupsRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedEmailsRoute: typeof AuthenticatedEmailsRoute
  AuthenticatedQueuesRoute: typeof AuthenticatedQueuesRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedTimelineRoute: typeof AuthenticatedTimelineRoute
  DTokenRoute: typeof DTokenRoute
  STokenRoute: typeof STokenRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedContainersBoxIdRoute: typeof AuthenticatedContainersBoxIdRoute
  AuthenticatedKeywordsKeywordIdRoute: typeof AuthenticatedKeywordsKeywordIdRoute
  AuthenticatedLettersArchiveIdRoute: typeof AuthenticatedLettersArchiveIdRoute
  AuthenticatedPeoplePersonIdRoute: typeof AuthenticatedPeoplePersonIdRoute
  AuthenticatedPlacesPlaceIdRoute: typeof AuthenticatedPlacesPlaceIdRoute
  AuthenticatedSourcesDsIdRoute: typeof AuthenticatedSourcesDsIdRoute
  AuthenticatedSourcesNewRoute: typeof AuthenticatedSourcesNewRoute
  ApiPublicBackupRoute: typeof ApiPublicBackupRoute
  AuthenticatedContainersIndexRoute: typeof AuthenticatedContainersIndexRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedKeywordsIndexRoute: typeof AuthenticatedKeywordsIndexRoute
  AuthenticatedLettersIndexRoute: typeof AuthenticatedLettersIndexRoute
  AuthenticatedOrganizationsIndexRoute: typeof AuthenticatedOrganizationsIndexRoute
  AuthenticatedPeopleIndexRoute: typeof AuthenticatedPeopleIndexRoute
  AuthenticatedPlacesIndexRoute: typeof AuthenticatedPlacesIndexRoute
  AuthenticatedSourcesIndexRoute: typeof AuthenticatedSourcesIndexRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/backups': {
      id: '/_authenticated/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthenticatedBackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/emails': {
      id: '/_authenticated/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof AuthenticatedEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/queues': {
      id: '/_authenticated/queues'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof AuthenticatedQueuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/timeline': {
      id: '/_authenticated/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthenticatedTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$token': {
      id: '/d/$token'
      path: '/d/$token'
      fullPath: '/d/$token'
      preLoaderRoute: typeof DTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/containers/': {
      id: '/_authenticated/containers/'
      path: '/containers'
      fullPath: '/containers/'
      preLoaderRoute: typeof AuthenticatedContainersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/containers/$boxId': {
      id: '/_authenticated/containers/$boxId'
      path: '/containers/$boxId'
      fullPath: '/containers/$boxId'
      preLoaderRoute: typeof AuthenticatedContainersBoxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/keywords/': {
      id: '/_authenticated/keywords/'
      path: '/keywords'
      fullPath: '/keywords/'
      preLoaderRoute: typeof AuthenticatedKeywordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/keywords/$keywordId': {
      id: '/_authenticated/keywords/$keywordId'
      path: '/keywords/$keywordId'
      fullPath: '/keywords/$keywordId'
      preLoaderRoute: typeof AuthenticatedKeywordsKeywordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/letters/': {
      id: '/_authenticated/letters/'
      path: '/letters'
      fullPath: '/letters/'
      preLoaderRoute: typeof AuthenticatedLettersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/letters/$archiveId': {
      id: '/_authenticated/letters/$archiveId'
      path: '/letters/$archiveId'
      fullPath: '/letters/$archiveId'
      preLoaderRoute: typeof AuthenticatedLettersArchiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/organizations/': {
      id: '/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/people/': {
      id: '/_authenticated/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthenticatedPeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/people/$personId': {
      id: '/_authenticated/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AuthenticatedPeoplePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/places/': {
      id: '/_authenticated/places/'
      path: '/places'
      fullPath: '/places/'
      preLoaderRoute: typeof AuthenticatedPlacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/places/$placeId': {
      id: '/_authenticated/places/$placeId'
      path: '/places/$placeId'
      fullPath: '/places/$placeId'
      preLoaderRoute: typeof AuthenticatedPlacesPlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sources/': {
      id: '/_authenticated/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof AuthenticatedSourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sources/$dsId': {
      id: '/_authenticated/sources/$dsId'
      path: '/sources/$dsId'
      fullPath: '/sources/$dsId'
      preLoaderRoute: typeof AuthenticatedSourcesDsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sources/new': {
      id: '/_authenticated/sources/new'
      path: '/sources/new'
      fullPath: '/sources/new'
      preLoaderRoute: typeof AuthenticatedSourcesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backup': {
      id: '/api/public/backup'
      path: '/api/public/backup'
      fullPath: '/api/public/backup'
      preLoaderRoute: typeof ApiPublicBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthenticatedBackupsRoute: AuthenticatedBackupsRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedEmailsRoute: AuthenticatedEmailsRoute,
  AuthenticatedQueuesRoute: AuthenticatedQueuesRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedTimelineRoute: AuthenticatedTimelineRoute,
  DTokenRoute: DTokenRoute,
  STokenRoute: STokenRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedContainersBoxIdRoute: AuthenticatedContainersBoxIdRoute,
  AuthenticatedKeywordsKeywordIdRoute: AuthenticatedKeywordsKeywordIdRoute,
  AuthenticatedLettersArchiveIdRoute: AuthenticatedLettersArchiveIdRoute,
  AuthenticatedPeoplePersonIdRoute: AuthenticatedPeoplePersonIdRoute,
  AuthenticatedPlacesPlaceIdRoute: AuthenticatedPlacesPlaceIdRoute,
  AuthenticatedSourcesDsIdRoute: AuthenticatedSourcesDsIdRoute,
  AuthenticatedSourcesNewRoute: AuthenticatedSourcesNewRoute,
  ApiPublicBackupRoute: ApiPublicBackupRoute,
  AuthenticatedContainersIndexRoute: AuthenticatedContainersIndexRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedKeywordsIndexRoute: AuthenticatedKeywordsIndexRoute,
  AuthenticatedLettersIndexRoute: AuthenticatedLettersIndexRoute,
  AuthenticatedOrganizationsIndexRoute: AuthenticatedOrganizationsIndexRoute,
  AuthenticatedPeopleIndexRoute: AuthenticatedPeopleIndexRoute,
  AuthenticatedPlacesIndexRoute: AuthenticatedPlacesIndexRoute,
  AuthenticatedSourcesIndexRoute: AuthenticatedSourcesIndexRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
