/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBackupsRouteImport } from './routes/_authenticated/backups'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedEmailsRouteImport } from './routes/_authenticated/emails'
import { Route as AuthenticatedQueuesRouteImport } from './routes/_authenticated/queues'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedTimelineRouteImport } from './routes/_authenticated/timeline'
import { Route as ContainersBoxIdRouteImport } from './routes/containers/$boxId'
import { Route as DTokenRouteImport } from './routes/d.$token'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as KeywordsIndexRouteImport } from './routes/keywords/index'
import { Route as KeywordsKeywordIdRouteImport } from './routes/keywords/$keywordId'
import { Route as LettersIndexRouteImport } from './routes/letters/index'
import { Route as LettersArchiveIdRouteImport } from './routes/letters/$archiveId'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as PeopleIndexRouteImport } from './routes/people/index'
import { Route as PeoplePersonIdRouteImport } from './routes/people/$personId'
import { Route as PlacesIndexRouteImport } from './routes/places/index'
import { Route as PlacesPlaceIdRouteImport } from './routes/places/$placeId'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as SourcesIndexRouteImport } from './routes/sources/index'
import { Route as SourcesDsIdRouteImport } from './routes/sources/$dsId'
import { Route as SourcesNewRouteImport } from './routes/sources/new'
import { Route as AuthenticatedContainersIndexRouteImport } from './routes/_authenticated/containers/index'
import { Route as ApiPublicBackupRouteImport } from './routes/api/public/backup'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBackupsRoute = AuthenticatedBackupsRouteImport.update({
  id: '/_authenticated/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/_authenticated/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/_authenticated/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEmailsRoute = AuthenticatedEmailsRouteImport.update({
  id: '/_authenticated/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQueuesRoute = AuthenticatedQueuesRouteImport.update({
  id: '/_authenticated/queues',
  path: '/queues',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/_authenticated/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimelineRoute = AuthenticatedTimelineRouteImport.update({
  id: '/_authenticated/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersBoxIdRoute = ContainersBoxIdRouteImport.update({
  id: '/containers/$boxId',
  path: '/containers/$boxId',
  getParentRoute: () => rootRouteImport,
} as any)
const DTokenRoute = DTokenRouteImport.update({
  id: '/d/$token',
  path: '/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsIndexRoute = KeywordsIndexRouteImport.update({
  id: '/keywords/',
  path: '/keywords/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsKeywordIdRoute = KeywordsKeywordIdRouteImport.update({
  id: '/keywords/$keywordId',
  path: '/keywords/$keywordId',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersIndexRoute = LettersIndexRouteImport.update({
  id: '/letters/',
  path: '/letters/',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersArchiveIdRoute = LettersArchiveIdRouteImport.update({
  id: '/letters/$archiveId',
  path: '/letters/$archiveId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesIndexRoute = PlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesPlaceIdRoute = PlacesPlaceIdRouteImport.update({
  id: '/places/$placeId',
  path: '/places/$placeId',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesDsIdRoute = SourcesDsIdRouteImport.update({
  id: '/sources/$dsId',
  path: '/sources/$dsId',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesNewRoute = SourcesNewRouteImport.update({
  id: '/sources/new',
  path: '/sources/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContainersIndexRoute =
  AuthenticatedContainersIndexRouteImport.update({
    id: '/_authenticated/containers/',
    path: '/containers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBackupRoute = ApiPublicBackupRouteImport.update({
  id: '/api/public/backup',
  path: '/api/public/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/queues': typeof AuthenticatedQueuesRoute
  '/search': typeof AuthenticatedSearchRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/containers/$boxId': typeof ContainersBoxIdRoute
  '/d/$token': typeof DTokenRoute
  '/keywords/$keywordId': typeof KeywordsKeywordIdRoute
  '/letters/$archiveId': typeof LettersArchiveIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/places/$placeId': typeof PlacesPlaceIdRoute
  '/s/$token': typeof STokenRoute
  '/sources/$dsId': typeof SourcesDsIdRoute
  '/sources/new': typeof SourcesNewRoute
  '/': typeof AuthenticatedIndexRoute
  '/events/': typeof EventsIndexRoute
  '/keywords/': typeof KeywordsIndexRoute
  '/letters/': typeof LettersIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/api/public/backup': typeof ApiPublicBackupRoute
  '/containers/': typeof AuthenticatedContainersIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/queues': typeof AuthenticatedQueuesRoute
  '/search': typeof AuthenticatedSearchRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/containers/$boxId': typeof ContainersBoxIdRoute
  '/d/$token': typeof DTokenRoute
  '/keywords/$keywordId': typeof KeywordsKeywordIdRoute
  '/letters/$archiveId': typeof LettersArchiveIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/places/$placeId': typeof PlacesPlaceIdRoute
  '/s/$token': typeof STokenRoute
  '/sources/$dsId': typeof SourcesDsIdRoute
  '/sources/new': typeof SourcesNewRoute
  '/': typeof AuthenticatedIndexRoute
  '/events': typeof EventsIndexRoute
  '/keywords': typeof KeywordsIndexRoute
  '/letters': typeof LettersIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/people': typeof PeopleIndexRoute
  '/places': typeof PlacesIndexRoute
  '/sources': typeof SourcesIndexRoute
  '/api/public/backup': typeof ApiPublicBackupRoute
  '/containers': typeof AuthenticatedContainersIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/backups': typeof AuthenticatedBackupsRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/emails': typeof AuthenticatedEmailsRoute
  '/_authenticated/queues': typeof AuthenticatedQueuesRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/timeline': typeof AuthenticatedTimelineRoute
  '/containers/$boxId': typeof ContainersBoxIdRoute
  '/d/$token': typeof DTokenRoute
  '/keywords/$keywordId': typeof KeywordsKeywordIdRoute
  '/letters/$archiveId': typeof LettersArchiveIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/places/$placeId': typeof PlacesPlaceIdRoute
  '/s/$token': typeof STokenRoute
  '/sources/$dsId': typeof SourcesDsIdRoute
  '/sources/new': typeof SourcesNewRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/events/': typeof EventsIndexRoute
  '/keywords/': typeof KeywordsIndexRoute
  '/letters/': typeof LettersIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/api/public/backup': typeof ApiPublicBackupRoute
  '/_authenticated/containers/': typeof AuthenticatedContainersIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/backups'
    | '/catalog'
    | '/categories'
    | '/emails'
    | '/queues'
    | '/search'
    | '/timeline'
    | '/containers/$boxId'
    | '/d/$token'
    | '/keywords/$keywordId'
    | '/letters/$archiveId'
    | '/people/$personId'
    | '/places/$placeId'
    | '/s/$token'
    | '/sources/$dsId'
    | '/sources/new'
    | '/'
    | '/events/'
    | '/keywords/'
    | '/letters/'
    | '/organizations/'
    | '/people/'
    | '/places/'
    | '/sources/'
    | '/api/public/backup'
    | '/containers/'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/backups'
    | '/catalog'
    | '/categories'
    | '/emails'
    | '/queues'
    | '/search'
    | '/timeline'
    | '/containers/$boxId'
    | '/d/$token'
    | '/keywords/$keywordId'
    | '/letters/$archiveId'
    | '/people/$personId'
    | '/places/$placeId'
    | '/s/$token'
    | '/sources/$dsId'
    | '/sources/new'
    | '/'
    | '/events'
    | '/keywords'
    | '/letters'
    | '/organizations'
    | '/people'
    | '/places'
    | '/sources'
    | '/api/public/backup'
    | '/containers'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/backups'
    | '/_authenticated/catalog'
    | '/_authenticated/categories'
    | '/_authenticated/emails'
    | '/_authenticated/queues'
    | '/_authenticated/search'
    | '/_authenticated/timeline'
    | '/containers/$boxId'
    | '/d/$token'
    | '/keywords/$keywordId'
    | '/letters/$archiveId'
    | '/people/$personId'
    | '/places/$placeId'
    | '/s/$token'
    | '/sources/$dsId'
    | '/sources/new'
    | '/_authenticated/'
    | '/events/'
    | '/keywords/'
    | '/letters/'
    | '/organizations/'
    | '/people/'
    | '/places/'
    | '/sources/'
    | '/api/public/backup'
    | '/_authenticated/containers/'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthenticatedBackupsRoute: typeof AuthenticatedBackupsRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedEmailsRoute: typeof AuthenticatedEmailsRoute
  AuthenticatedQueuesRoute: typeof AuthenticatedQueuesRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedTimelineRoute: typeof AuthenticatedTimelineRoute
  ContainersBoxIdRoute: typeof ContainersBoxIdRoute
  DTokenRoute: typeof DTokenRoute
  KeywordsKeywordIdRoute: typeof KeywordsKeywordIdRoute
  LettersArchiveIdRoute: typeof LettersArchiveIdRoute
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  PlacesPlaceIdRoute: typeof PlacesPlaceIdRoute
  STokenRoute: typeof STokenRoute
  SourcesDsIdRoute: typeof SourcesDsIdRoute
  SourcesNewRoute: typeof SourcesNewRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  KeywordsIndexRoute: typeof KeywordsIndexRoute
  LettersIndexRoute: typeof LettersIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  PlacesIndexRoute: typeof PlacesIndexRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
  ApiPublicBackupRoute: typeof ApiPublicBackupRoute
  AuthenticatedContainersIndexRoute: typeof AuthenticatedContainersIndexRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/backups': {
      id: '/_authenticated/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthenticatedBackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/emails': {
      id: '/_authenticated/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof AuthenticatedEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/queues': {
      id: '/_authenticated/queues'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof AuthenticatedQueuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/timeline': {
      id: '/_authenticated/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthenticatedTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/$boxId': {
      id: '/containers/$boxId'
      path: '/containers/$boxId'
      fullPath: '/containers/$boxId'
      preLoaderRoute: typeof ContainersBoxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$token': {
      id: '/d/$token'
      path: '/d/$token'
      fullPath: '/d/$token'
      preLoaderRoute: typeof DTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords/': {
      id: '/keywords/'
      path: '/keywords'
      fullPath: '/keywords/'
      preLoaderRoute: typeof KeywordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords/$keywordId': {
      id: '/keywords/$keywordId'
      path: '/keywords/$keywordId'
      fullPath: '/keywords/$keywordId'
      preLoaderRoute: typeof KeywordsKeywordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters/': {
      id: '/letters/'
      path: '/letters'
      fullPath: '/letters/'
      preLoaderRoute: typeof LettersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters/$archiveId': {
      id: '/letters/$archiveId'
      path: '/letters/$archiveId'
      fullPath: '/letters/$archiveId'
      preLoaderRoute: typeof LettersArchiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/': {
      id: '/places/'
      path: '/places'
      fullPath: '/places/'
      preLoaderRoute: typeof PlacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$placeId': {
      id: '/places/$placeId'
      path: '/places/$placeId'
      fullPath: '/places/$placeId'
      preLoaderRoute: typeof PlacesPlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$dsId': {
      id: '/sources/$dsId'
      path: '/sources/$dsId'
      fullPath: '/sources/$dsId'
      preLoaderRoute: typeof SourcesDsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/new': {
      id: '/sources/new'
      path: '/sources/new'
      fullPath: '/sources/new'
      preLoaderRoute: typeof SourcesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/containers/': {
      id: '/_authenticated/containers/'
      path: '/containers'
      fullPath: '/containers/'
      preLoaderRoute: typeof AuthenticatedContainersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backup': {
      id: '/api/public/backup'
      path: '/api/public/backup'
      fullPath: '/api/public/backup'
      preLoaderRoute: typeof ApiPublicBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthenticatedBackupsRoute: AuthenticatedBackupsRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedEmailsRoute: AuthenticatedEmailsRoute,
  AuthenticatedQueuesRoute: AuthenticatedQueuesRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedTimelineRoute: AuthenticatedTimelineRoute,
  ContainersBoxIdRoute: ContainersBoxIdRoute,
  DTokenRoute: DTokenRoute,
  KeywordsKeywordIdRoute: KeywordsKeywordIdRoute,
  LettersArchiveIdRoute: LettersArchiveIdRoute,
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  PlacesPlaceIdRoute: PlacesPlaceIdRoute,
  STokenRoute: STokenRoute,
  SourcesDsIdRoute: SourcesDsIdRoute,
  SourcesNewRoute: SourcesNewRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  KeywordsIndexRoute: KeywordsIndexRoute,
  LettersIndexRoute: LettersIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  PlacesIndexRoute: PlacesIndexRoute,
  SourcesIndexRoute: SourcesIndexRoute,
  ApiPublicBackupRoute: ApiPublicBackupRoute,
  AuthenticatedContainersIndexRoute: AuthenticatedContainersIndexRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
